version: "2.4"

volumes:
  postgres-data:

services:

#  api:
#    build:
#      context: server
#      dockerfile: dev.Dockerfile
#      args:
#        NODE_VERSION:
#        APP_VERSION:
#    volumes:
#      - ./server:/home/app
#    links:
#      - postgres:postgres.local
#    ports:
#      - 4000:4000
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
